apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka-http
  labels:
     app: akka
spec:
 selector:
   matchLabels:
      app: akka
 replicas: 2
 template:
    metadata:
      labels:
        app: akka
    spec:
      containers:
      - name: akka-con
        image: vidushi0808/akka-http
        ports:
        - containerPort: 8090       
